// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TFOR_IOS
{
	public partial class MonitorScreenController : UIViewController
	{
		SiteModel siteModel { get; set; }
        public Site[] Sitesarr { get; set; }

        public MonitorScreenController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
			///Instatiates the required objects to make the Picker view work
			siteModel = new SiteModel(Sitesarr);
			MonitorSitePickerView.Model = siteModel;

			base.ViewWillAppear(animated);
        }
    }
}
