// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TFOR_IOS
{
	public partial class SurveyScreenController : UIViewController
	{
		public Site[] Sitesarr { get; set; }
		public SiteModel SiteMod { get; private set; }
		
		public SurveyScreenController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear(bool animated)
        {
			base.ViewWillAppear(animated);

			SiteMod = new SiteModel(Sitesarr);
			SSitePickerView.Model = SiteMod;

        }
    }
}
