// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TFOR_IOS
{
	public partial class SurveySubmitButton : UIButton
	{
		public SurveySubmitButton (IntPtr handle) : base (handle)
		{
		}
	}
}
